jobs:
  build:
    runs-on: ubuntu-latest  # CI 서버에서 Ubuntu 사용

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # 3. Gradle 설치
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '7.5.1'

      # 4. Docker Compose 설치
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 5. Docker Compose로 ELK Stack 실행
      - name: Start ELK Stack with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d  # ELK Stack 시작

      # 6. Gradle 빌드 및 테스트 실행
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests with Gradle
        run: ./gradlew test --no-daemon

      # 7. ELK Stack 상태 확인 (선택 사항)
      - name: Check Elasticsearch status
        run: curl -X GET "http://localhost:9200/_cluster/health?pretty"
